### ISSUE TITLE
ZNE 8.6.0 and zmantis 1.13 : bug in main display panel 

### ISSUE THREAD

**Issue by edhil** [irontec/zmantis#5] opened 2016-08-23 12:57 UTC
When trying to deploy zmantis 1.13 on a ZNE 8.6.0 server, we have the following issue : 
Even when is zimlet is disabled by CoS, some users on the server cannot change their Reading Panel in the 'View' settings. 
If they change the Reading pane from default right to "Right", then the main panel is not updated when the user try to show emails from a different folder or delete an email. 

If the user change back the Reading Panel to "Right", and log out/log in, the reading panel is ok. 

The only way to get rid of this issue is by undeploying the zmantis zimlet from the CLI and by restarting mailboxd service.

**Comment by Kaian** [comment] 2016-08-23 14:22
Hi @edhil !

I have give it a try to the steps you mention and seems to be also reproducible in zimbra 8.5.0
In my tests, the problem seems that zMantis includes a jQuery minimized javascript 1.6 in its source and other zimlets require a more recent one.

We require jQuery for token-input plugin (the fancy input boxes with autocomplete), but It looks like including it in the source may clash with other zimlets doing the same thing. I will try to investigate if there is a better way to include jquery dependency.

Anyway, if you have the time, give it a try to 1.1.14 (a mailbox restart may be required).

Thanks for reporting!!

**Comment by edhil** [comment] 2016-08-23 15:00
Hi Kaian ! 

I've just deployed 1.1.14 version, and it seems to work perfectly so far ! 
Many thanks for your prompt support, all my "bottom-panel fan" colleagues will be pleased. 
(and so do I, as zMantis is a great time-saver for support!) 

Greetings!

**Comment by Kaian** [comment] 2016-08-23 15:10
Nice, I'll close this then.

Feel free to open any other issue for whatever you need.
Best regards!

**Closed by Kaian** 2016-08-23 15:10 UTC
Labels: bug
